[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Paulo", email = "bruh@bruh.bruh"},
]
dependencies = [
    "django>=4.1.7",
]
requires-python = ">=3.10"
license = {text = "MIT"}
