# Generated by Django 4.2.4 on 2023-08-08 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("livraria", "0002_livro_capa"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="livro",
            name="categorias",
        ),
        migrations.AddField(
            model_name="livro",
            name="categoria",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="livros",
                to="livraria.categoria",
            ),
            preserve_default=False,
        ),
    ]
