# Generated by Django 4.1.7 on 2023-03-17 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0010_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
